<?php
define("KWH_UNITARIO_EOLICO", 2.5);
define("KWH_UNITARIO_HIDRICO", 3.5);
define("KWH_UNITARIO_SOLAR", 5);
define("PRECO_UNITARIO_EOLICO", 15000);
define("PRECO_UNITARIO_HIDRICO", 10000);
define("PRECO_UNITARIO_SOLAR", 5000);
define("PRECO_UNITARIO_BATERIA", 3000);
?>
